### ISSUE TITLE
怎么使用啊？有没有大佬解释一下

### ISSUE THREAD

**Issue by SVIPPANDA** [elseif/MikroTikPatch#1]
不明觉厉，请求解惑

**Comment by ShuanLotus** [comment]
下载安装,使用,粘贴,激活,完事

**Comment by SVIPPANDA** [comment]
谢谢您的回复，虽然没有任何帮助。

**Comment by ShuanLotus** [comment]
> 谢谢您的回复，虽然没有任何帮助。

1:首先下载iso或者是img,

**Comment by ShuanLotus** [comment]
> > 谢谢您的回复，虽然没有任何帮助。
> 
> 1:首先下载iso或者是img,进入安装界面之后直接按p选择安装所有

2:然后下载keygen.zip,
3:进入routeros,在system license查看自己的硬盘id
4:在keygen.exe的目录使用cmd,keygen.exe 空格  再复制自己的硬盘id,  最后回车,
5:将生成的密钥复制,最后在routeros里面导入,系统会自动重启重启完之后就可以了

**Comment by SVIPPANDA** [comment]
谢谢您！！ISO安装方式，我已经测试成功了！同样感谢您的无私回复！祝您万事如意！好人一生平安！
![Snipaste_2024-06-18_02-17-41](https://github.com/elseif/MikroTikPatch/assets/152469797/1a28f365-3ee9-404e-bef4-adda8b0834c9)

非常简单，打开cmd，进入keygen.exe目录  输入keygen.exe xxx-xxx  把生成的KEY复制粘贴到ros terminal 重启后就看到等级6了

**Comment by Urmi10799** [comment]
> keygen.zip

can't find keygen.zip

**Comment by ShuanLotus** [comment]
> > keygen.zip
> 
> can't find keygen.zip

please read radme
