### ISSUE TITLE
请问,能否添加Qemu-GA的组件

### ISSUE THREAD

**Issue by Kotori-0912** [elseif/MikroTikPatch#13]
因为需要部署到PVE或者Esxi上面，但是缺少Qemu-GA或者VM-tools组件，导致虚拟机无法正常关机

**Comment by elseif** [comment]
目前还没改造routeros的计划，不过为什么会不能关机呢，winbox里reboot也重启不了吗？

**Comment by Kotori-0912** [comment]
> 目前还没改造routeros的计划，不过为什么会不能关机呢，winbox里reboot也重启不了吗？

因为有时候物理主机需要关机，直接使用虚拟化的控制面板执行关机
