### ISSUE TITLE
使用patch后的镜像无法使用在线更新

### ISSUE THREAD

**Issue by shanghaojia-1** [elseif/MikroTikPatch#18]
在线更新会提示broken package，只能下载patch后的镜像手动上传更新，这部分能否优化下

**Comment by elseif** [comment]
刚刚发布的7.15.2最新版已经支持在线更新，chr镜像支持在线授权

**Comment by shanghaojia-1** [comment]
好的，我就是7.15.1手动升级到7.15.2的
