### ISSUE TITLE
netinstall 安装有问题

### ISSUE THREAD

**Issue by sswking** [elseif/MikroTikPatch#19]
使用netinstall安装方式 提示
![屏幕截图 2024-07-06 132613](https://github.com/elseif/MikroTikPatch/assets/22900861/920498bd-5377-4720-a545-070f392a7326)
请教下如何正确安装
x86平台

**Comment by elseif** [comment]
你试试官方的原版程序呢？

**Comment by elseif** [comment]
悄悄的告诉你，官方的提供的这个netinstall仅支持UEFI下的PXE引导，不支持BIOS模式

**Comment by sswking** [comment]
明白，那可能就是这个问题了。感谢
