### ISSUE TITLE
Can we the hack ROS program to skip DUID detection?

### ISSUE THREAD

**Issue by capricornxl** [elseif/MikroTikPatch#23]
+ Problem 1: Many regions in China have started using vBRAS, but the DUID is not in the format defined by RFC, so it is directly rejected by ROS.   
log report: `Bad server DUID`

+ Problem 2: A custom DUID is provided through DHCP CLIENT OPTIONS, but ROS also considers it unusable.    
log report: `Bad client duid`

**Comment by elseif** [comment]
no

**Comment by wsgtrsys** [comment]
直接对它的程序打补丁有可能行。

**Comment by capricornxl** [comment]
> 直接对它的程序打补丁有可能行。

dhcpclient程序我这已经尝试处理了，但是需要重新签名所有NPK和替换公钥。
应该需要重新解包再封包routeros的npk

**Comment by capricornxl** [comment]
@elseif 大佬，MIKRO_CLOUD_PUBLIC_KEY，这个是在什么时候会用到？
如果我想跑自己的Actions这个需要关注吗？
