### ISSUE TITLE
解决了，怎么删？

### ISSUE THREAD

**Issue by killtrump** [elseif/MikroTikPatch#27]
我设置了一下admin用户的密码，现在admin只能是在admin组别，无法更改到full组别，我看系统默认有一个用户名是system的是full组别的，请问这个System账号的密码是多少？谢谢
![system](https://github.com/user-attachments/assets/ba157403-6429-4988-ad73-d50c1e115fca)

**Comment by killtrump** [comment]
解决了，估计是被人黑进来改了

**Comment by qq20967582** [comment]
安装在云上，一下就被扫。

**Comment by killtrump** [comment]
> 安装在云上，一下就被扫。

我是本地安装，但我有公网ip，安装1个小时都不到，扫描器太快了，有好的防火墙脚本吗？
