### ISSUE TITLE
请教下patch后，系统里多了个System用户？

### ISSUE THREAD

**Issue by vevechen** [elseif/MikroTikPatch#33]
请教各位大佬：

System用户的权限是full，admin降级为admin。
请问这个System用户有啥用？密码为啥？

谢谢

**Comment by elseif** [comment]
跟patch没关系，没有这个用户，你应该是没修改密码挂在公网了

**Comment by elseif** [comment]
https://github.com/elseif/MikroTikPatch/issues/27#issue-2438567017
