### ISSUE TITLE
可以指定版本来跑workflows么？

### ISSUE THREAD

**Issue by Fddh2012** [elseif/MikroTikPatch#4]
可以指定版本来跑workflows么？
如题哈，另外就是想问一下，是不是群友啊？

**Comment by elseif** [comment]
你可以修改workflow让获取最新版本返回一个固定的版本号就可以了

**Comment by Fddh2012** [comment]
> 你可以修改workflow让获取最新版本返回一个固定的版本号就可以了
> 
> * name: Get latest routeros version
>   run: |
>   LATEST_VERSION=“7.14”
>   echo Latest Version:$LATEST_VERSION
>   echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV

Got it, 3Q!

**Comment by elseif** [comment]
最新的workflow已经支持输入版本号，留空自动获取最新的

**Comment by Fddh2012** [comment]
> 最新的workflow已经支持输入版本号，留空自动获取最新的

爱死你了！！
