### ISSUE TITLE
netinstall支持arm mips系列的routerboard替换公钥吗？

### ISSUE THREAD

**Issue by wsgtrsys** [elseif/MikroTikPatch#6]
本来已经有routerboard了，就不必用这个了吧。
但只有替换了公钥才有可能获取到shell。
试了用netinstall安装到routerboard上，好象还是原来的公钥。

**Comment by elseif** [comment]
你用patch过的netinstall网络安装要用patch过的npk文件。netinstall在patch的时候已经全架构patch过了。
